"""initial_schema

Revision ID: 716f2ca1b437
Revises: 
Create Date: 2026-09-08 23:08:51.687992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '716f2ca1b437'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('manufacturer_name', sa.String(length=255), nullable=True),
    sa.Column('manufacturer_address', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('rule_configs',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('regex_pattern', sa.String(length=500), nullable=True),
    sa.Column('min_font_height_mm', sa.Float(), nullable=True),
    sa.Column('placement_zone', sa.String(length=100), nullable=True),
    sa.Column('language_requirement', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Inspector', 'Reviewer', 'Admin', name='role_enum'), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('scans',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('raw_image_path', sa.Text(), nullable=True),
    sa.Column('preprocessed_image_path', sa.Text(), nullable=True),
    sa.Column('capture_timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'done', 'needs_review', 'error', name='scan_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_table('declarations',
    sa.Column('declaration_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.Enum('MRP', 'net_quantity', 'mfg_date', 'manufacturer_address', 'consumer_care', 'unit_sale_price', 'dimensions', name='field_name_enum'), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('font_height_mm', sa.Float(), nullable=True),
    sa.Column('language_detected', sa.String(length=20), nullable=True),
    sa.Column('is_manually_corrected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('declaration_id')
    )
    op.create_table('inspection_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('compliance_status', sa.Enum('compliant', 'non_compliant', 'needs_review', name='compliance_enum'), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('docx_path', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'sent_back', 'escalated', name='report_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_table('violations',
    sa.Column('violation_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('declaration_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('missing', 'format', 'font', 'placement', 'misleading', 'language', name='violation_category_enum'), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'minor', name='severity_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['declarations.declaration_id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rule_configs.rule_id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('violation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violations')
    op.drop_table('inspection_reports')
    op.drop_table('declarations')
    op.drop_table('scans')
    op.drop_table('users')
    op.drop_table('rule_configs')
    op.drop_table('products')
    # ### end Alembic commands ###
